### PR TITLE
Fix segfault

### PR DESCRIPTION
**Pull request by xitep**
Seems like the conversion to a `Vec<u8>` should not be allowed by `lmdb-rs`. At least, this quickly fixes your issue. [vhbit/lmdb-rs/issues/29](https://github.com/vhbit/lmdb-rs/issues/29).

### CODE REVIEW

**Comment by code-ape** [comment]
You are correct! That fixes everything. I'll take a look at `lmdb-rs` later and see why it allows `Vec<u8>` casting.

**Comment by xitep** [comment]
I'm not entirely sure, but i think the culprit is this one (in lmdb_rs):

```
impl FromMdbValue for Vec<u8> {
    fn from_mdb_value(value: &MdbValue) -> Vec<u8> {
        unsafe {
            Vec::from_raw_parts(mem::transmute(value.get_ref()),
                                value.get_size(),
                                value.get_size())
        }
    }
}
```

if I traced it correctly the `value` parameter is a pointer into mmapped memory by lmdb. So when such a `Vec<u8>` gets dropped ... boom! it seems almost to easy an explanation (i suspect i'm wrong).

One more problem with this implementation is also that it can outlive the memory pointed to by `value`. especially in your example this seems to be the case, as you have very short lived readers and try to access the data even after you've closed them.

I'm not very much into the internals of lmdb-rs, but it seems to me like this `Vec<u8>` implementation should make a copy of the data. However, in that case I'd suggest to drop the implementation entirely and leave it up to users to make copy of the data. This would make them aware of the performance penalty. @vhbit what do you think?

**Comment by code-ape** [comment]
I am still somewhat new to working with really low level stuff. So please correct me if I'm wrong. I suspect it may be an issue with how Vec's work in Rust. I don't know if this relates to heap vs stack operations and pointers but I suspect this is not an issue with mmapping as if it were the case then it would also fail for the `&[u8]` allocation which also uses it's own, near identical, `::from_raw_parts(...)`. I was thinking that these should both work identically, but when I looked up the method for transforming a slice to a `Vec` I found [this](https://github.com/rust-lang/rust/blob/4b615854f00ba17ad704155e1d3196c17a6edb62/src/libcollections/slice.rs#L139):

``` Rust
pub fn into_vec<T>(mut b: Box<[T]>) -> Vec<T> {
    unsafe {
        let xs = Vec::from_raw_parts(b.as_mut_ptr(), b.len(), b.len());
        mem::forget(b);
        xs
    }
}
```

I'm not sure if the `men::forget(b)` is an important difference or not. But it's the only one I could find.

Also upon examining [docs for `Vec::from_raw_parts`](https://doc.rust-lang.org/std/vec/struct.Vec.html#safety) there seems to be a strong case that there may just be an issue with trying to cast the original data directly to a Vec:

> This is highly unsafe, due to the number of invariants that aren't checked:
> - ptr needs to have been previously allocated via String/Vec<T> (at least, it's highly likely to be incorrect if it wasn't).
> - length needs to be the length that less than or equal to capacity.
> - capacity needs to be the capacity that the pointer was allocated with.
> 
> Violating these may cause problems like corrupting the allocator's internal data structures.

It seems like the lifetime of the Vec may also have something to do with this issue, [see here](https://mail.mozilla.org/pipermail/rust-dev/2014-December/011439.html), where when the Vec goes out of scope all data related to it does as well. Maybe this could be fixed by casting to a slice and then converting to a `Vec`? I'm not sure.

PS - should this conversation be moved over to the vhbit/lmdb-rs#29?

**Comment by xitep** [comment]
my suspicion - unfortunately i don't have time to further investigate at the moment - is that for `&[u8]` the `Drop` implementation doesn't do anything (that's why it works in your case), whereas for `Vec<u8>` it frees the pointed to memory, but that memory was not allocated by rust but was provided by lmdb through a mmapped memory segment.

in the `into_vec` example you have shown, the `mem::forget(b)` is indeed very important. it causes that the memory pointed to by `Box<[T]>` is _not_ freed when the function returns. the trick here is that that memory gets moved (manually) into the returned `Vec<T>`, which then once it is subject to dropping will free that memory.

oh, yes ... let's further continue on the ticket.

**Pull request merged**
